# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

tasks:
  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --fix
      - go run mvdan.cc/gofumpt@latest -w -l .
      - go run github.com/dkorunic/betteralign/cmd/betteralign@latest -test_files -generated_files -apply ./...